# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "41d300d6a3a17cefb1ef8d1a7d1b8da1"
application_url = "https://mobiles-portrait-instrumentation-lou.trycloudflare.com"
embedded = true
name = "checkout-hitarth"
handle = "checkout-hitarth"

[webhooks]
api_version = "2024-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://mobiles-portrait-instrumentation-lou.trycloudflare.com/auth/callback",
  "https://mobiles-portrait-instrumentation-lou.trycloudflare.com/auth/shopify/callback",
  "https://mobiles-portrait-instrumentation-lou.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "demo-hitarth-3.myshopify.com"
automatically_update_urls_on_dev = true
